import { Company } from './companies-table/company';

export const COMPANIES: Company[] = [
  {
    "CompanyID": 62,
    "Name": "Daytona",
    "DateCreated": "2011-12-28T12:19:59",
    "DateModified": "2011-12-28T12:19:59",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 2,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 65,
    "Name": "InPocketExpense",
    "DateCreated": "2011-12-28T12:49:25",
    "DateModified": "2012-01-01T10:03:09",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 66,
    "Name": "Email Testing",
    "DateCreated": "2012-01-04T07:12:15",
    "DateModified": "2012-01-04T07:12:15",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 68,
    "Name": "Itemization",
    "DateCreated": "2012-01-06T18:25:19",
    "DateModified": "2012-01-06T18:25:19",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 69,
    "Name": "ExpensePath, inc",
    "DateCreated": "2012-01-08T14:28:39",
    "DateModified": "2012-01-08T14:28:39",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 8,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 70,
    "Name": "Chrome Test",
    "DateCreated": "2012-01-11T07:26:42",
    "DateModified": "2012-01-11T07:26:42",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 71,
    "Name": "testing safari",
    "DateCreated": "2012-01-11T08:50:17",
    "DateModified": "2012-01-11T08:50:17",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 72,
    "Name": "Firefox test",
    "DateCreated": "2012-01-12T07:31:58",
    "DateModified": "2012-01-12T07:31:58",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 73,
    "Name": "IE testing",
    "DateCreated": "2012-01-13T08:00:07",
    "DateModified": "2012-01-13T08:00:07",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 75,
    "Name": "Cantaloupe Systems, Inc",
    "DateCreated": "2012-01-19T00:48:11",
    "DateModified": "2012-01-19T00:48:11",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 77,
    "Name": "Itemization  Testing3",
    "DateCreated": "2012-01-23T03:00:58",
    "DateModified": "2012-01-23T03:00:58",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 78,
    "Name": "VikeLTestIE",
    "DateCreated": "2012-01-23T16:17:47",
    "DateModified": "2012-01-23T16:17:47",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 2,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 79,
    "Name": "Khasali IE9",
    "DateCreated": "2012-01-24T18:00:35",
    "DateModified": "2012-01-24T18:00:35",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 82,
    "Name": "Pacesetter Claims",
    "DateCreated": "2012-02-01T17:02:52",
    "DateModified": "2012-02-01T17:02:52",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 83,
    "Name": "Andrew IE8",
    "DateCreated": "2012-02-02T15:00:53",
    "DateModified": "2012-02-02T15:00:53",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 85,
    "Name": "VictorKZ Test Company",
    "DateCreated": "2012-03-04T06:00:29",
    "DateModified": "2012-03-04T06:00:29",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 4,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 88,
    "Name": "Disconnect, Inc.",
    "DateCreated": "2012-04-06T05:46:39",
    "DateModified": "2012-04-06T05:46:39",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 4,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 89,
    "Name": "Andrew Base Testing",
    "DateCreated": "2012-04-24T18:18:08",
    "DateModified": "2012-04-24T18:18:08",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 90,
    "Name": "Evalueserve",
    "DateCreated": "2012-04-26T18:23:34",
    "DateModified": "2012-04-26T18:23:34",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 91,
    "Name": "Apple inc.",
    "DateCreated": "2012-05-21T20:40:43",
    "DateModified": "2012-05-21T20:40:43",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 2,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 93,
    "Name": "Test Khasali ",
    "DateCreated": "2012-05-29T11:52:20",
    "DateModified": "2012-05-29T11:52:20",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 94,
    "Name": "M1 eL Test",
    "DateCreated": "2012-05-29T23:24:22",
    "DateModified": "2012-05-29T23:24:22",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 95,
    "Name": "M1 eL PC Test",
    "DateCreated": "2012-05-29T23:27:38",
    "DateModified": "2012-05-29T23:27:38",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 96,
    "Name": "TSP Testing",
    "DateCreated": "2012-06-04T08:57:02",
    "DateModified": "2012-06-04T08:57:02",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 100,
    "Name": "Demo Company",
    "DateCreated": "2012-06-22T04:01:34",
    "DateModified": "2012-06-22T04:01:34",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 8,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 101,
    "Name": "M1Serious",
    "DateCreated": "2012-06-24T00:18:26",
    "DateModified": "2012-06-24T00:18:26",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 102,
    "Name": "TubeWriter",
    "DateCreated": "2012-07-13T05:44:10",
    "DateModified": "2012-07-13T05:44:10",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 103,
    "Name": "Foghorn Consulting",
    "DateCreated": "2012-07-13T06:31:09",
    "DateModified": "2012-07-13T06:31:09",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 4,
    "Status": 2,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 104,
    "Name": "Merging",
    "DateCreated": "2012-08-03T11:27:04",
    "DateModified": "2012-08-03T11:27:04",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 106,
    "Name": "M2 eL Release",
    "DateCreated": "2012-08-12T14:57:31",
    "DateModified": "2012-08-12T14:57:31",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 2,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 107,
    "Name": "Vik Aug Test",
    "DateCreated": "2012-08-17T05:12:49",
    "DateModified": "2012-08-17T05:12:49",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 108,
    "Name": "Waterfall Mobile, Inc.",
    "DateCreated": "2012-09-11T03:36:54",
    "DateModified": "2012-09-11T03:36:54",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 109,
    "Name": "BillPin",
    "DateCreated": "2012-09-12T01:09:30",
    "DateModified": "2012-09-12T01:09:30",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 4,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 110,
    "Name": "TrustLink",
    "DateCreated": "2012-09-18T17:58:38",
    "DateModified": "2012-09-18T17:58:38",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 111,
    "Name": "Sunil Trial",
    "DateCreated": "2012-09-18T18:04:16",
    "DateModified": "2012-09-18T18:04:16",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 4,
    "Status": 2,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 112,
    "Name": "Sunpreme",
    "DateCreated": "2012-09-21T04:58:16",
    "DateModified": "2012-09-21T04:58:16",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 113,
    "Name": "TSP",
    "DateCreated": "2012-09-21T10:06:20",
    "DateModified": "2012-09-21T10:06:20",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 114,
    "Name": "Sep Test Co",
    "DateCreated": "2012-09-21T15:21:07",
    "DateModified": "2012-09-21T15:21:07",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 115,
    "Name": "Test TP",
    "DateCreated": "2012-09-21T15:36:11",
    "DateModified": "2012-09-21T15:36:11",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 116,
    "Name": "Sample Company",
    "DateCreated": "2012-09-25T06:42:19",
    "DateModified": "2012-09-25T06:42:19",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 8,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 117,
    "Name": "Lab49",
    "DateCreated": "2012-09-29T05:51:09",
    "DateModified": "2012-09-29T05:51:09",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 118,
    "Name": "SooCho Test",
    "DateCreated": "2012-10-16T23:18:09",
    "DateModified": "2012-10-16T23:18:09",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 4,
    "Status": 2,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 119,
    "Name": "BlueJeans Network",
    "DateCreated": "2012-10-31T17:47:40",
    "DateModified": "2012-10-31T17:47:40",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 120,
    "Name": "Test Company - TSP",
    "DateCreated": "2012-11-05T04:53:31",
    "DateModified": "2012-11-05T04:53:31",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 122,
    "Name": "M4 create test2",
    "DateCreated": "2012-11-22T02:50:36",
    "DateModified": "2012-11-22T02:50:36",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 123,
    "Name": "M4 create test3",
    "DateCreated": "2012-11-22T03:42:36",
    "DateModified": "2012-11-22T03:42:36",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 124,
    "Name": "RheoGrid",
    "DateCreated": "2012-11-22T04:36:58",
    "DateModified": "2012-11-22T04:36:58",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 4,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 125,
    "Name": "The Brix Group",
    "DateCreated": "2012-12-04T06:53:22",
    "DateModified": "2012-12-04T06:53:22",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 126,
    "Name": "151 Advisors",
    "DateCreated": "2012-12-06T20:50:24",
    "DateModified": "2012-12-06T20:50:24",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 127,
    "Name": "M4 Release",
    "DateCreated": "2012-12-10T07:38:34",
    "DateModified": "2012-12-10T07:38:34",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 128,
    "Name": "Fibrogen",
    "DateCreated": "2012-12-18T01:41:34",
    "DateModified": "2012-12-18T01:41:34",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 4,
    "Status": 2,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 129,
    "Name": "Test TSP",
    "DateCreated": "2012-12-21T07:04:07",
    "DateModified": "2012-12-21T07:04:07",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 130,
    "Name": "Parature Inc.",
    "DateCreated": "2013-01-02T06:52:34",
    "DateModified": "2013-01-02T06:52:34",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 131,
    "Name": "1.19 Release",
    "DateCreated": "2013-01-17T16:55:13",
    "DateModified": "2013-01-17T16:55:13",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 2,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 132,
    "Name": "No ER Company",
    "DateCreated": "2013-01-28T04:33:32",
    "DateModified": "2013-01-28T04:33:32",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 133,
    "Name": "Agiliance, Inc.",
    "DateCreated": "2013-01-30T23:06:06",
    "DateModified": "2013-01-30T23:06:06",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 134,
    "Name": "July Systems",
    "DateCreated": "2013-02-11T22:35:49",
    "DateModified": "2013-02-11T22:35:49",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 135,
    "Name": "Export Company",
    "DateCreated": "2013-02-12T22:58:34",
    "DateModified": "2013-02-12T22:58:34",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 136,
    "Name": "ProjCode Company",
    "DateCreated": "2013-02-13T17:42:36",
    "DateModified": "2013-02-13T17:42:36",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 2,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 137,
    "Name": "Skybox Security, Inc.",
    "DateCreated": "2013-02-13T18:59:39",
    "DateModified": "2013-02-13T18:59:39",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 138,
    "Name": "Cycle Approver Testing",
    "DateCreated": "2013-02-20T19:10:28",
    "DateModified": "2013-02-20T19:10:28",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 139,
    "Name": "Marie's testing",
    "DateCreated": "2013-02-24T23:58:38",
    "DateModified": "2013-02-24T23:58:38",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 141,
    "Name": "SOASTA, Inc.",
    "DateCreated": "2013-03-06T05:52:22",
    "DateModified": "2013-03-06T05:52:22",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 143,
    "Name": "InsideVault, Inc",
    "DateCreated": "2013-03-08T13:38:29",
    "DateModified": "2013-03-08T13:38:29",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 144,
    "Name": "eL0308",
    "DateCreated": "2013-03-08T14:30:42",
    "DateModified": "2013-03-08T14:30:42",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 1,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 146,
    "Name": "R0310",
    "DateCreated": "2013-03-10T21:07:39",
    "DateModified": "2013-03-10T21:07:39",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 147,
    "Name": "Moka5, Inc.",
    "DateCreated": "2013-03-19T00:25:17",
    "DateModified": "2013-03-19T00:25:17",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 148,
    "Name": "Mocana Corporation",
    "DateCreated": "2013-03-25T05:47:12",
    "DateModified": "2013-03-25T05:47:12",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 149,
    "Name": "QBO Testing",
    "DateCreated": "2013-04-01T16:18:08",
    "DateModified": "2013-04-01T16:18:08",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 150,
    "Name": "Policy Testing",
    "DateCreated": "2013-04-15T17:06:03",
    "DateModified": "2013-04-15T17:06:03",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 151,
    "Name": "Intuit",
    "DateCreated": "2013-05-07T19:34:08",
    "DateModified": "2013-05-07T19:34:08",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 8,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 152,
    "Name": "Administrators",
    "DateCreated": "2013-05-08T15:47:50",
    "DateModified": "2013-05-08T15:47:50",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 8,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 153,
    "Name": "QBDesktop",
    "DateCreated": "2013-06-29T20:22:39",
    "DateModified": "2013-06-29T20:22:39",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 8,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 154,
    "Name": "Digital Air Strike",
    "DateCreated": "2013-07-19T05:39:57",
    "DateModified": "2013-07-19T05:39:57",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 155,
    "Name": "User",
    "DateCreated": "2013-07-31T20:36:17",
    "DateModified": "2013-07-31T20:36:17",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 8,
    "Status": 2,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 156,
    "Name": "Mobeam, Inc.",
    "DateCreated": "2013-08-16T04:07:51",
    "DateModified": "2013-08-16T04:07:51",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 157,
    "Name": "DASTest",
    "DateCreated": "2013-08-26T22:34:39",
    "DateModified": "2013-08-26T22:34:39",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 1,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 158,
    "Name": "RW Mercer Co",
    "DateCreated": "2013-09-21T18:19:47",
    "DateModified": "2013-09-21T18:19:47",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 159,
    "Name": "Interra Systems, Inc.",
    "DateCreated": "2013-09-26T04:59:07",
    "DateModified": "2013-09-26T04:59:07",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 160,
    "Name": "Paul Miller Test Co.",
    "DateCreated": "2013-09-26T07:50:23",
    "DateModified": "2013-09-26T07:50:23",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 4,
    "Status": 2,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 161,
    "Name": "Bunndle, Inc.",
    "DateCreated": "2013-10-25T07:03:25",
    "DateModified": "2013-10-25T07:03:25",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 162,
    "Name": "Boreal Genomics",
    "DateCreated": "2013-10-25T07:25:59",
    "DateModified": "2013-10-25T07:25:59",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1162,
    "Name": "Intacct testing",
    "DateCreated": "2013-11-02T14:33:15",
    "DateModified": "2013-11-02T14:33:15",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1163,
    "Name": "Instart Logic, Inc.",
    "DateCreated": "2013-11-05T23:52:24",
    "DateModified": "2013-11-05T23:52:24",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1164,
    "Name": "Social Finance",
    "DateCreated": "2013-11-11T06:18:46",
    "DateModified": "2013-11-11T06:18:46",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1165,
    "Name": "FX test company",
    "DateCreated": "2013-11-17T22:31:49",
    "DateModified": "2013-11-17T22:31:49",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1166,
    "Name": "Common Sense Media",
    "DateCreated": "2014-02-05T05:42:27",
    "DateModified": "2014-02-05T05:42:27",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1167,
    "Name": "Feb 2014",
    "DateCreated": "2014-02-05T06:06:42",
    "DateModified": "2014-02-05T06:06:42",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 1,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1168,
    "Name": "Passare, Inc.",
    "DateCreated": "2014-02-20T06:36:05",
    "DateModified": "2014-02-20T06:36:05",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1169,
    "Name": "Buddhist Churches of America",
    "DateCreated": "2014-03-05T07:28:50",
    "DateModified": "2014-03-05T07:28:50",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1170,
    "Name": "mCordis",
    "DateCreated": "2014-03-06T01:28:56",
    "DateModified": "2014-03-06T01:28:56",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1171,
    "Name": "Act-On Software, Inc.",
    "DateCreated": "2014-03-06T07:02:44",
    "DateModified": "2014-03-06T07:02:44",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1172,
    "Name": "643 Capital Mgmt",
    "DateCreated": "2014-03-25T21:51:30",
    "DateModified": "2014-03-25T21:51:30",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1173,
    "Name": "Maker Media, Inc.",
    "DateCreated": "2014-03-27T01:53:22",
    "DateModified": "2014-03-27T01:53:22",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1174,
    "Name": "WealthEngine",
    "DateCreated": "2014-05-21T18:49:57",
    "DateModified": "2014-05-21T18:49:57",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1175,
    "Name": "Suncrest Solar",
    "DateCreated": "2014-05-27T20:34:35",
    "DateModified": "2014-05-27T20:34:35",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1176,
    "Name": "ATEL Financial Services",
    "DateCreated": "2014-07-16T04:31:00",
    "DateModified": "2014-07-16T04:31:00",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1177,
    "Name": "Prism Skylabs, Inc.",
    "DateCreated": "2014-07-24T07:44:36",
    "DateModified": "2014-07-24T07:44:36",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1178,
    "Name": "Sachin Test Company",
    "DateCreated": "2014-08-11T17:55:04",
    "DateModified": "2014-08-11T17:55:04",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 4,
    "Status": 1,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1179,
    "Name": "Steep Hill Halent",
    "DateCreated": "2014-10-22T06:37:55",
    "DateModified": "2014-10-22T06:37:55",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1180,
    "Name": "Merlone Geier",
    "DateCreated": "2014-11-16T09:48:45",
    "DateModified": "2014-11-16T09:48:45",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 2,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1181,
    "Name": "Actify, Inc.",
    "DateCreated": "2014-12-12T06:45:52",
    "DateModified": "2014-12-12T06:45:52",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1182,
    "Name": "Paramount Sports",
    "DateCreated": "2014-12-22T05:46:26",
    "DateModified": "2014-12-22T05:46:26",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1183,
    "Name": "Mobile Health Consumer",
    "DateCreated": "2015-01-18T07:11:02",
    "DateModified": "2015-01-18T07:11:02",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1184,
    "Name": "ExpensePath Support",
    "DateCreated": "2015-02-03T06:20:27",
    "DateModified": "2015-02-03T06:20:27",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 8,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1185,
    "Name": "PitchBook Data, Inc.",
    "DateCreated": "2015-02-04T17:29:25",
    "DateModified": "2015-02-04T17:29:25",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1186,
    "Name": "UnitedWeb",
    "DateCreated": "2015-02-20T07:09:28",
    "DateModified": "2015-02-20T07:09:28",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1187,
    "Name": "Four Five One Events",
    "DateCreated": "2015-03-27T03:28:55",
    "DateModified": "2015-03-27T03:28:55",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1188,
    "Name": "Conrad Imports, Inc.",
    "DateCreated": "2015-04-01T17:18:43",
    "DateModified": "2015-04-01T17:18:43",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1189,
    "Name": "ClearCare Inc.",
    "DateCreated": "2015-04-07T01:04:06",
    "DateModified": "2015-04-07T01:04:06",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1190,
    "Name": "Belle Aire Baptist Church",
    "DateCreated": "2015-04-16T06:02:03",
    "DateModified": "2015-04-16T06:02:03",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1191,
    "Name": "WaveFront, Inc.",
    "DateCreated": "2015-04-29T04:27:36",
    "DateModified": "2015-04-29T04:27:36",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1192,
    "Name": "Integrated Life Choices",
    "DateCreated": "2015-06-04T04:52:21",
    "DateModified": "2015-06-04T04:52:21",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1193,
    "Name": "BizRev",
    "DateCreated": "2015-06-16T05:39:56",
    "DateModified": "2015-06-16T05:39:56",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 4,
    "Status": 1,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1194,
    "Name": "Grace Presbyterian Church",
    "DateCreated": "2015-06-24T06:04:35",
    "DateModified": "2015-06-24T06:04:35",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1195,
    "Name": "Camden Capital LLC",
    "DateCreated": "2015-06-25T16:29:40",
    "DateModified": "2015-06-25T16:29:40",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1196,
    "Name": "Colorado Uplift",
    "DateCreated": "2015-07-01T04:04:14",
    "DateModified": "2015-07-01T04:04:14",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1197,
    "Name": "Blue River Coatings",
    "DateCreated": "2015-07-02T08:11:03",
    "DateModified": "2015-07-02T08:11:03",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1198,
    "Name": "Can Do Enterprises",
    "DateCreated": "2015-07-11T05:46:40",
    "DateModified": "2015-07-11T05:46:40",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1199,
    "Name": "Connance, Inc.",
    "DateCreated": "2015-07-17T05:25:53",
    "DateModified": "2015-07-17T05:25:53",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1200,
    "Name": "Tax Executives Institute, Inc.",
    "DateCreated": "2015-08-01T05:25:06",
    "DateModified": "2015-08-01T05:25:06",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1201,
    "Name": "Transmodal Corporation",
    "DateCreated": "2015-08-07T01:56:36",
    "DateModified": "2015-08-07T01:56:36",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1202,
    "Name": "Glenbrook",
    "DateCreated": "2015-08-08T07:11:59",
    "DateModified": "2015-08-08T07:11:59",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1203,
    "Name": "QBO_20150812",
    "DateCreated": "2015-08-12T22:54:38",
    "DateModified": "2015-08-12T22:54:38",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 1,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1204,
    "Name": "Lantz Medical",
    "DateCreated": "2015-09-06T05:49:32",
    "DateModified": "2015-09-06T05:49:32",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1205,
    "Name": "0915",
    "DateCreated": "2015-09-09T12:50:16",
    "DateModified": "2015-09-09T12:50:16",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 1,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1206,
    "Name": "clear.md",
    "DateCreated": "2015-09-11T18:03:01",
    "DateModified": "2015-09-11T18:03:01",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1207,
    "Name": "LG Chem",
    "DateCreated": "2015-09-13T07:48:16",
    "DateModified": "2015-09-13T07:48:16",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1208,
    "Name": "Emerald City Pizza",
    "DateCreated": "2015-09-17T05:28:35",
    "DateModified": "2015-09-17T05:28:35",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1209,
    "Name": "Cure Forward",
    "DateCreated": "2015-09-22T22:48:01",
    "DateModified": "2015-09-22T22:48:01",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1210,
    "Name": "Maryknoll Lay Missioners",
    "DateCreated": "2015-09-22T22:54:37",
    "DateModified": "2015-09-22T22:54:37",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1211,
    "Name": "Michigan Broadband",
    "DateCreated": "2015-09-26T19:26:53",
    "DateModified": "2015-09-26T19:26:53",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1212,
    "Name": "M6",
    "DateCreated": "2015-10-02T04:09:01",
    "DateModified": "2015-10-02T04:09:01",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 2,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1213,
    "Name": "American Lumber",
    "DateCreated": "2015-10-06T04:37:51",
    "DateModified": "2015-10-06T04:37:51",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1214,
    "Name": "IDEC Corporation",
    "DateCreated": "2015-10-11T04:59:36",
    "DateModified": "2015-10-11T04:59:36",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1215,
    "Name": "PC Mag Test",
    "DateCreated": "2015-10-15T06:51:17",
    "DateModified": "2015-10-15T06:51:17",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1216,
    "Name": "Hatteras",
    "DateCreated": "2015-10-15T15:59:37",
    "DateModified": "2015-10-15T15:59:37",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1217,
    "Name": "Luna Vineyards",
    "DateCreated": "2015-10-27T04:03:26",
    "DateModified": "2015-10-27T04:03:26",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1218,
    "Name": "The Town Church",
    "DateCreated": "2015-10-27T04:07:32",
    "DateModified": "2015-10-27T04:07:32",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1219,
    "Name": "GEP",
    "DateCreated": "2015-11-07T06:15:14",
    "DateModified": "2015-11-07T06:15:14",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1220,
    "Name": "VillageReach",
    "DateCreated": "2015-11-18T05:39:35",
    "DateModified": "2015-11-18T05:39:35",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1221,
    "Name": "Whitehouse & Schapiro",
    "DateCreated": "2015-11-24T18:35:57",
    "DateModified": "2015-11-24T18:35:57",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1222,
    "Name": "Ralph Andersen & Associates",
    "DateCreated": "2015-12-22T20:15:28",
    "DateModified": "2015-12-22T20:15:28",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1223,
    "Name": "Ralph Andersen",
    "DateCreated": "2015-12-22T20:53:33",
    "DateModified": "2015-12-22T20:53:33",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 16,
    "Status": 1,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1224,
    "Name": "SaintA, Inc.",
    "DateCreated": "2016-01-06T04:38:56",
    "DateModified": "2016-01-06T04:38:56",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1225,
    "Name": "Rubixis Inc.",
    "DateCreated": "2016-01-15T05:18:03",
    "DateModified": "2016-01-15T05:18:03",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 2,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1226,
    "Name": "Virtual Hold Technology",
    "DateCreated": "2016-01-28T05:43:55",
    "DateModified": "2016-01-28T05:43:55",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1227,
    "Name": "Jewish Family & Career Services",
    "DateCreated": "2016-02-07T07:53:06",
    "DateModified": "2016-02-07T07:53:06",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1228,
    "Name": "Crimson Chemicals, Inc.",
    "DateCreated": "2016-02-08T18:00:42",
    "DateModified": "2016-02-08T18:00:42",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1229,
    "Name": "Right Start Mortgage",
    "DateCreated": "2016-02-10T19:02:46",
    "DateModified": "2016-02-10T19:02:46",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 3,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1230,
    "Name": "CC Jensen",
    "DateCreated": "2016-02-25T21:47:39",
    "DateModified": "2016-02-25T21:47:39",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1231,
    "Name": "AV Design Services, LLC",
    "DateCreated": "2016-03-11T17:28:33",
    "DateModified": "2016-03-11T17:28:33",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 1,
    "Status": 4,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
  {
    "CompanyID": 1232,
    "Name": "Y&R Demo",
    "DateCreated": "2016-03-14T05:22:50",
    "DateModified": "2016-03-14T05:22:50",
    "IsBlocked": false,
    "TimeZoneId": null,
    "TimeZone": null,
    "CompanyProfile": null,
    "AccountType": 8,
    "Status": 1,
    "BaseCurrency": null,
    "SpecialOptions": 0,
    "Settings": null,
    "UserProfiles": [],
    "Categories": null,
    "ProjectCodes": null,
    "UserGroups": null,
    "AllCurrencies": null,
    "Departments": null
  },
]
